#' Cleans a member's highest earned degree.
#'
#' @param df a tibble of demographic data
#'
#' @return a tibble with cleaned column Highest_Degree
#' @export
#'
#' @examples
step_highestdegree <- function(df) {

  #df$Degree %>% replace_na("Not Specified")

  df <-
    df %>%
    mutate(
      Highest_Degree =
        recode_factor(
          .data$Degree,
          "Associates" = "Associates",
          "2 yrs of grad program" = "Bachelors",
          "bachelor 2020, MS" = "Bachelors",
          "Bachelor's of Science, Major: Artificial Intelligence, Bachelors" = "Bachelors",
          "Bachelors" = "Bachelors",
          "Bachelors, Diploma" = "Bachelors",
          "Bachelors, Organizational Behavior" = "Bachelors",
          "Bachelors, Post-Bac Program" = "Bachelors",
          "BCom Industrial and Organizational Psychology" = "Bachelors",
          "ABD, MS, PhD" = "Doctorate",
          "ABD, PhD" = "Doctorate",
          "Bachelors, MA, PhD" = "Doctorate",
          "Bachelors, MBA, MPhil, PhD" = "Doctorate",
          "Bachelors, MSC, PhD" = "Doctorate",
          "Bachelors, PhD" = "Doctorate",
          "DBA" = "Doctorate",
          "DBA, MS" = "Doctorate",
          "DBA, PhD" = "Doctorate",
          "DM" = "Doctorate",
          "Doctor of Public Health (DrPH)" = "Doctorate",
          "Dr. rer. nat." = "Doctorate",
          "Dr. rer. soc." = "Doctorate",
          "EdD" = "Doctorate",
          "EdD, MA" = "Doctorate",
          "EdS" = "Doctorate",
          "HonDrSc, PhD" = "Doctorate",
          "IO Psych, PhD" = "Doctorate",
          "JD, PhD" = "Doctorate",
          "JD/PhD" = "Doctorate",
          "MA, MS, PhD" = "Doctorate",
          "MA, PhD" = "Doctorate",
          "MA, PsyD" = "Doctorate",
          "MAIOP, PhD" = "Doctorate",
          "MBA, PhD" = "Doctorate",
          "MBA/MA, PhD" = "Doctorate",
          "MEd, MPA, PhD" = "Doctorate",
          "MS, PhD" = "Doctorate",
          "MSC, PhD" = "Doctorate",
          "PhD" = "Doctorate",
          "PhD, Postdoc" = "Doctorate",
          "PsyD" = "Doctorate",
          "Diploma" = "Other",
          "ABD" = "ABD",
          "ABD, MA" = "ABD",
          "ABD, MEd" = "ABD",
          "ABD, MS" = "ABD",
          "ALM" = "Masters",
          "Bachelors, MA" = "Masters",
          "Bachelors, MA, MS" = "Masters",
          "Bachelors, MAIOP" = "Masters",
          "Bachelors, MBA" = "Masters",
          "Bachelors, MEd" = "Masters",
          "Bachelors, MHRIR" = "Masters",
          "Bachelors, MOD" = "Masters",
          "Bachelors, MS" = "Masters",
          "Bachelors, MSC" = "Masters",
          "Bachelors, MSW" = "Masters",
          "Certificate , MEd" = "Masters",
          "Erasmus Mundi" = "Masters",
          "Erasmus Mundus Joint Master Degree in Work, Organizational and Personnel Psychology (EMJMD WOP-P" = "Masters",
          "Executive Master of Science In  Industrial Organizational Psychology and Management of Human Resources" = "Masters",
          "M.Litt" = "Masters",
          "M.S. Business Psychology , MS" = "Masters",
          "M.Soc.Sc." = "Masters",
          "M.Soc.Sci" = "Masters",
          "MA" = "Masters",
          "MA, MBA" = "Masters",
          "MA, MBA/MS" = "Masters",
          "MA, MEd" = "Masters",
          "MA, MS" = "Masters",
          "MA/cand.psychol." = "Masters",
          "MAA" = "Masters",
          "MAE" = "Masters",
          "MAIO" = "Masters",
          "MAIOP" = "Masters",
          "MAIOP, MS" = "Masters",
          "MAOP" = "Masters",
          "MAP" = "Masters",
          "MAppPsy" = "Masters",
          "MASc" = "Masters",
          "Master Degree" = "Masters",
          "Master in Human Development" = "Masters",
          "Master of Applied Industrial Organizational Psychology" = "Masters",
          "MASTER OF HUMAN RESOURCES MANAGEMENT" = "Masters",
          "Master of Managerial Psychology" = "Masters",
          "Master of Professional Studies (M.P.S.)" = "Masters",
          "Master of Science in Human Resources" = "Masters",
          "Master of Science in I/O Psychology" = "Masters",
          "Master of Science Psychology with Concentration I/O Psychology, MS" = "Masters",
          "Master’s of Liberal Arts in Extension studies, I-O Psychology" = "Masters",
          "Masters In Human Development (MHD), MBA" = "Masters",
          "Masters of Industrial and Labor Relations" = "Masters",
          "Masters of Industrial Organizational Psychology" = "Masters",
          "Masters of Professional Studies in IO Psychology" = "Masters",
          "Masters of Psychology Organisational and Human Factors" = "Masters",
          "MBA" = "Masters",
          "MBA, MS" = "Masters",
          "MBA/MA" = "Masters",
          "MBA/MS" = "Masters",
          "MBA/MS, MS" = "Masters",
          "MBBS" = "Masters",
          "MC" = "Masters",
          "MCOM" = "Masters",
          "MD" = "Masters",
          "MEd" = "Masters",
          "MHRIR" = "Masters",
          "MOD" = "Masters",
          "MOP" = "Masters",
          "MPA" = "Masters",
          "MPH" = "Masters",
          "MPhil" = "Masters",
          "MPP" = "Masters",
          "MPs" = "Masters",
          "MPSIO" = "Masters",
          "MS" = "Masters",
          "MS, Post-Baccalaureate Certificate" = "Masters",
          "MSC" = "Masters",
          "MSE" = "Masters",
          "MSIOP" = "Masters",
          "MSOL" = "Masters",
          "MSOP" = "Masters",
          "MSP" = "Masters",
          "MSW" = "Masters",
          "PGD (MBA HR)" = "Masters",
          "Post-Master’s I/O Certification" = "Masters",
          "Cand. Psychol" = "Other",
          "Cand. psychol., PsyD" = "Other",
          "Certificate" = "Other",
          "Certificate in Industrial and Organizational Psychology" = "Other",
          "Certificate in Psychology  - School of Professional Studies" = "Other",
          "Diploma, Industrial and Organizational Psychology Generalist Certificate" = "Other",
          "Executive Managment" = "Other",
          "Generalist Certificate" = "Other",
          "Graduate Certificate" = "Other",
          "Graduate Certificate I-O Psychology" = "Other",
          "Graduate Certificate in I/O Psychology" = "Other",
          "Graduate Certificate in Industrial/Organizational Psychology" = "Other",
          "Industrial Organizational Psychology Graduate Certificate in Organizational Psychology" = "Other",
          "Industrial/Organizational Psychology Graduate Certificate" = "Other",
          "Instructional Design Graduate Certificate, MA" = "Other",
          "Meeting Prerequisites for Graduate School" = "Other",
          "Organizational Behavior Master's Certificate" = "Other",
          "Other" = "Other",
          "PgDip" = "Other",
          "PHR Certification and Prep course" = "Other",
          "Strategic Decision and Risk Management Certificate" = "Other",
          "Bachelors, JD, LLB (Bachelor of Laws)" = "Other",
          "JD" = "Other",
          "JD, MA" = "Other",
          "JD, Masters in Industrial and Organizational Psychology" = "Other",
          "JD, MS" = "Other",
          "JD/MBA" = "Other",
          "JD/MBA, post bachelor - research assistant" = "Other"
        )
    ) %>%
    return()

}
